version: '3.7'

services:
  db:
    image: postgres:10
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:4
    restart: always
    volumes:
      - redis_data:/var/lib/redis

  web:
    build: .
    command: bash ./docker-entrypount.sh
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD:
    # network_mode: host
    env_file:
      - sendgrid.env
    ports:
      - "3012:3012"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD:
    # network_mode: host
    env_file:
      - sendgrid.env

volumes:
  pg_data:
  redis_data: