default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'marketing_sg' %>
  username: <%= ENV['DB_USERNAME'] || 'marketing_sg' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'marketing_sg_test' %>
  username: <%= ENV['DB_USERNAME'] || 'marketing_sg' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
